[Todo-8] Han, Ellie 2차 풀리퀘 보내드립니다
codesquad-member-2020/todo-8 pull request #102
Opened 2020-04-16 08:27 UTC by bohyeon-n

구현 사항 
- 카드 수정, 이동 
- activity 로그 기능 추가 
- column 추가, 삭제, 수정 기능 
- CORS 설정 
- 리팩토링

2020-04-19 08:12 UTC, wheejuni requested changes
수고 많으셨습니다.
`List` 의 메소드들 다양하게 사용해보신 것 인상적이네요.

간단한 수정사항 남겨드렸으니 도움 되었으면 좋겠습니다.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/configure/CorsConfig.java
> +        long MAX_AGE_SECS = 3600;
하나의 메소드에서만 사용되는 상수값이라면 굳이 이렇게 관리하지 않아도 됩니다.
`.maxAge(3600)` 처럼 하셔도 됩니다.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/controller/TodoRestController.java
> +//    Long id = getUserId(request);
주석 제거 부탁드려요.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/controller/authentication/JwtInterceptor.java
>  //    if (validationToken(jwt)) {
주석 제거해주세요.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/Activity.java
> +  private final Long arrival;
엔티티 클래스의 필드가 `final` 이여야할 이유가 있을까요. 
값이 바뀔 때마다 새로운 객체를 생성하게 되는 건가요.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/Activity.java
> +  Activity withId(Long id) {
접근제어자가 빠졌네요. 붙여주세요.

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/Activity.java
> +    return Objects.equal(id, activity.id);
`id` 필드는 `private` 아니었나요?

2020-04-19 08:12 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/repository/ActivityRepository.java
> +      + "LIMIT 15")
쿼리 보기좋게 정리하신 것 좋네요!

2020-04-20 03:19 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/model/Activity.java
> +  private final Long arrival;
https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/#jdbc.entity-persistence
이 문서를 참고하여 작성하셨습니다. 생각해보면 굳이 새로운 객체를 생성할 필요는 없을 것 같아 보여요.

2020-04-20 03:20 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/model/Activity.java
> +    return Objects.equal(id, activity.id);
그렇네요. ㅠㅠ

2020-04-20 03:20 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/repository/ActivityRepository.java
> +      + "LIMIT 15")
감사합니다~

2020-04-21 02:34 UTC, merged