[BE] 1차 풀리퀘 보내드립니다
codesquad-member-2020/todo-8 pull request #63
Opened 2020-04-10 07:15 UTC by 102092

### 구현사항
- interceptor를 이용한 jwt에서 userName 추출하기
- 메인 페이지 (로그포함)
- 카드 생성, 삭제

### 앞으로 할 일
- 카드 수정, 이동 기능
- 로그 생성 기능
- mysql과 연결
- Master 브랜치에 배포
- 필수적인 에러 처리
- 리팩토링

2020-04-11 06:22 UTC, wheejuni requested changes
중간점검성 풀리퀘였던 것 같은데 작업량이 적지 않네요. 
수고 많으셨습니다. 

JWT 관련한 로직은 주석으로 빼놓으셨던데 아직 미완성인 건가요. ㅎㅎ
맞는 방향으로 잘 가고 있는 것 같으니 그대로 진행하시면 될 것 같아요. 
코멘트드린 사항은 아주 사소한 개선점들 발견해서 남겨드리는 것이니 참고해주세요.

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/configure/WebConfig.java
> +        .excludePathPatterns("/h2-console/**")
`healthcheck` 도 interceptor 빠져도 되지 않을까요.

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/controller/JwtInterceptor.java
> +    if (jwt != null) {
스프링이 제공하는 `StringUtils.isEmpty()` 사용해 주세요.

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/controller/JwtInterceptor.java
> +    return false;
`Optional` 객체이므로 바로 `.isPresent()` 로 리턴하면 되지 않을까요?

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/controller/TodoRestController.java
> +      user = userService.getUserByName(userName).orElseThrow(NotFoundException::new);
굳이 여기서 `try-catch` 하지 말고 핸들러 메소드까지 올린 다음, `@ControllerAdvice` 로 처리하는 방식은 어떨까요?

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/Card.java
> +  public Card(Long id, Long categoryId, String author, String title, String contents,
static builder method를 쓸 거라면, 이렇게 모든 필드를 받는 생성자는 `private` 으로 숨기는 것도 좋습니다.

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/CardRequest.java
> +public class CardRequest {
흠 아직 `setter` 가 없군요. 미완성인거겠죠?

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/model/Category.java
> +    this.cards.add(0, card);
이것도 나쁘지 않은 방법이지만, `Card` 객체 자체가 `Comparable` 을 구현하거나 별도의 `Comparator` 를 구현하는 것이 더 좋은 방법일 거에요.

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/service/TodoService.java
> +    Card deletedCard = cardRepository.findById(cardId).get();
`.orElseThrow()` 사용해주세요. 혹은 `.orElse()`

2020-04-11 06:22 UTC, wheejuni commented on BE/src/main/java/com/codesquad/todo8/service/TodoService.java
> +    Category category = categoryRepository.findById(card.getCategoryId()).get();
`.orElseThrow()` 사용해주세요. 혹은 `.orElse()`

2020-04-12 04:43 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/configure/WebConfig.java
> +        .excludePathPatterns("/h2-console/**")
그렇네요!! 빼놓으면 편할듯해요. 반영하겠습니다~

2020-04-12 04:45 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/controller/TodoRestController.java
> +      user = userService.getUserByName(userName).orElseThrow(NotFoundException::new);
에러처리 부분에서  다룰 예정이었어요! 조언해주셔서 감사합니다 :)

2020-04-12 04:47 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/model/CardRequest.java
> +public class CardRequest {
아직 덜 완성된 부분입니다..ㅠㅠ

2020-04-12 04:48 UTC, 102092 commented on BE/src/main/java/com/codesquad/todo8/model/Category.java
> +    this.cards.add(0, card);
추가적으로 구현해보도록 하겠습니다!

2020-04-13 12:10 UTC, merged